In [1]:
import numpy as np

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.shape)

[1 2 3 4 5]
(5,)


In [13]:
print(arr.size)

8


In [14]:
print(arr.dtype)

int32


In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [15]:
print(arr.size)

8


In [16]:
print(arr.dtype)

int32


In [11]:
arr = np.array([[[3,7],[2,8]],[[1,4],[5,6]]])
print(arr)
print(arr.shape)

[[[3 7]
  [2 8]]

 [[1 4]
  [5 6]]]
(2, 2, 2)


In [12]:
print(arr.size)

8


In [17]:
print(arr.dtype)

int32


In [20]:
arr = np.array([1,5,8],dtype=np.float32)
arr

array([1., 5., 8.], dtype=float32)

In [21]:
print(arr.dtype)

float32


In [24]:
arr = np.array((1,2,3))
arr

array([1, 2, 3])

In [25]:
a = [1,3,4,5]
arr = np.asarray(a)
arr

array([1, 3, 4, 5])

In [26]:
a = (1,7,53,32)
arr = np.asarray(a)
arr

array([ 1,  7, 53, 32])

In [27]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [31]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [33]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
a = np.empty(5)
a

array([1., 1., 1., 1., 1.])

In [42]:
a = np.empty((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
a = np.empty((2,2,3))
a

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [52]:
x = np.arange(2,20,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
x = np.linspace(1,2,10)
x

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [54]:
x = np.eye(2)
x

array([[1., 0.],
       [0., 1.]])

In [56]:
x = np.eye(2,3)
x

array([[1., 0., 0.],
       [0., 1., 0.]])

In [61]:
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
a = np.array([1,7,6])
b = np.array([5,4,6])
a+b

array([ 6, 11, 12])

In [72]:
a*b

array([[[ 5, 10],
        [ 6, 14],
        [32, 32]]])

In [73]:
a/b

array([[[0.2       , 0.4       ],
        [0.66666667, 0.28571429],
        [0.5       , 0.5       ]]])

In [78]:
np.sqrt(a)

array([[[1.        , 1.41421356],
        [1.41421356, 1.41421356],
        [2.        , 2.        ]]])

In [79]:
np.sqrt(b)

array([[[2.23606798, 2.23606798],
        [1.73205081, 2.64575131],
        [2.82842712, 2.82842712]]])

In [66]:
a-b

array([[[-4, -3],
        [-1, -5],
        [-4, -4]]])

In [67]:
b-a

array([[[4, 3],
        [1, 5],
        [4, 4]]])

In [63]:
a = np.array([[1,6],[5,8]])
b = np.array([[5,2],[9,0]])
a+b

array([[ 6,  8],
       [14,  8]])

In [74]:
a*b

array([[[ 5, 10],
        [ 6, 14],
        [32, 32]]])

In [75]:
a/b

array([[[0.2       , 0.4       ],
        [0.66666667, 0.28571429],
        [0.5       , 0.5       ]]])

In [80]:
np.sqrt(a)

array([[[1.        , 1.41421356],
        [1.41421356, 1.41421356],
        [2.        , 2.        ]]])

In [81]:
np.sqrt(b)

array([[[2.23606798, 2.23606798],
        [1.73205081, 2.64575131],
        [2.82842712, 2.82842712]]])

In [68]:
a-b

array([[[-4, -3],
        [-1, -5],
        [-4, -4]]])

In [69]:
b-a

array([[[4, 3],
        [1, 5],
        [4, 4]]])

In [65]:
a = np.array([[[1,2],[2,2],[4,4]]])
b = np.array([[[5,5],[3,7],[8,8]]])
a+b

array([[[ 6,  7],
        [ 5,  9],
        [12, 12]]])

In [76]:
a*b

array([[[ 5, 10],
        [ 6, 14],
        [32, 32]]])

In [77]:
a/b

array([[[0.2       , 0.4       ],
        [0.66666667, 0.28571429],
        [0.5       , 0.5       ]]])

In [82]:
np.sqrt(a)

array([[[1.        , 1.41421356],
        [1.41421356, 1.41421356],
        [2.        , 2.        ]]])

In [83]:
np.sqrt(b)

array([[[2.23606798, 2.23606798],
        [1.73205081, 2.64575131],
        [2.82842712, 2.82842712]]])

In [70]:
a-b

array([[[-4, -3],
        [-1, -5],
        [-4, -4]]])

In [71]:
b-a

array([[[4, 3],
        [1, 5],
        [4, 4]]])

In [84]:
a = np.array([2,3,4])
b = 7
a+b

array([ 9, 10, 11])

In [85]:
b-a

array([5, 4, 3])

In [86]:
a-b

array([-5, -4, -3])

In [87]:
a/b

array([0.28571429, 0.42857143, 0.57142857])

In [88]:
a*b

array([14, 21, 28])

In [106]:
import time
from tqdm.auto import tqdm
x = np.random.rand(100000)
y = np.random.rand(100000)
start = time.time()
for i in tqdm(range(len(x))):
    x[i] + y[i]
end = time.time()
print(f"{end-start:.4f}")

  0%|          | 0/100000 [00:00<?, ?it/s]

0.0829


In [107]:
a = np.array([1, 2, 3, 4, 5])
b = np.resize(a, (3, 3))
print(b)

[[1 2 3]
 [4 5 1]
 [2 3 4]]


In [108]:
a = np.array([1, 2, 3, 4, 5])
b = np.resize(a, (3, 3))
print(b)

[[1 2 3]
 [4 5 1]
 [2 3 4]]


In [109]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)  

b = a.ravel()
print(b)  

(2, 3)
[1 2 3 4 5 6]
